/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useResource } from "react-three-fiber";
import { useLayoutEffect } from "react";
import { RepeatWrapping } from "three";
import { useState } from "react";
import { useEffect } from "react";

const colors = [
  ["#eee", "#eee", "#eee", "#ffa", "#eee"],
  ["pink", "hotpink", "hotpink", "pink", "pink"],
  ["#55aa33", "#00aaee", "#00aaee", "#00aaee", "#00aaee"],
  ["#ffa", "#55aa33", "#55aa33", "green", "green"],
  ["#00aaee", "#55aa33", "#eee", "pink", "#00aaee"],
];

function Light(props) {
  const ref = useResource();
  return (
    <>
      <mesh ref={ref} position={[0, 1, -10000]} />
      <spotLight
        intensity={1.3}
        distance={5}
        decay={3}
        penumbra={0.5}
        angle={Math.PI / 2}
        target={ref.current}
        {...props}
      />
    </>
  );
}

export default function Model(props) {
  const group = useRef();
  const structureMat = useResource();
  const screenMat = useResource();
  const { nodes } = useGLTF("/p.glb");
  const [marcello, setMarcello] = useState(0);

  const textures = useTexture([
    "/Concrete_Wall_007_ambientOcclusion.jpg",
    "/Concrete_Wall_007_normal.jpg",
    "/Concrete_Wall_007_roughness.jpg",
    "/Concrete_Wall_007_basecolor.jpg",
  ]);
  const screenTextures = useTexture([
    "/Metal012_2K_Roughness.jpg",
    "/Metal012_2K_Normal.jpg",
    "/Metal012_2K_Displacement.jpg",
    "/Metal012_2K_Metalness.jpg",
  ]);
  const screenMaps = useTexture([
    "/1.jpg",
    "/2.jpg",
    "/3.png",
    "/4.png",
    "/5.png",
  ]);
  const [ao, normal, roughness, base] = textures;
  const [
    screenRoughness,
    screenNormal,
    screenHeight,
    screenMetalness,
  ] = screenTextures;
  useLayoutEffect(() => {
    textures.forEach(
      (texture) =>
        void ((texture.wrapT = texture.wrapS = RepeatWrapping),
        texture.repeat.set(0.5, 0.5),
        texture.offset.set(-0.01, 0.008))
    );
  }, [textures]);

  useEffect(() => {
    const id = setInterval(
      () => setMarcello((s) => (s + 1) % colors.length),
      5000
    );
    return () => clearInterval(id);
  }, [setMarcello]);

  return (
    <>
      <meshStandardMaterial
        ref={structureMat}
        color="#333"
        roughness={0.9}
        metalness={0.7}
        envMapIntensity={3}
      />
      <meshPhysicalMaterial
        ref={screenMat}
        emissive="white"
        emissiveIntensity={0.05}
        metalness={0.5}
        roughness={1}
        clearcoat={1}
        envMapIntensity={5}
        map={screenMaps[marcello]}
        roughnessMap={screenRoughness}
        normalMap={screenNormal}
        normalScale={[0.1, 0.1]}
        displacementMap={screenHeight}
        metalnessMap={screenMetalness}
      />
      <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.Plane.geometry} position={[-1, 0, -2]}>
          <meshStandardMaterial
            color="#999"
            map={base}
            roughness={1}
            metalness={0.9}
            aoMap={ao}
            normalMap={normal}
            normalScale={[0.3, 0.3]}
            roughnessMap={roughness}
            envMapIntensity={5}
          />
        </mesh>
        <group
          position={[0.47, 0.58, 0.7]}
          rotation={[0, 0.38, 0]}
          scale={[-0.13, -0.65, -0.03]}
        >
          <mesh
            geometry={nodes.Cube001.geometry}
            material={structureMat.current}
          />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={screenMat.current}
          />
          <Light color={colors[marcello][0]} position={[2, 0, 0]} />
          <Light color={colors[marcello][1]} position={[-12, 0, -40]} />
          <Light color={colors[marcello][2]} position={[-25, 0, -80]} />
        </group>
        <group
          position={[2.65, 0.58, 0.01]}
          rotation={[0, 0.38, 0]}
          scale={[-0.13, -0.65, -0.03]}
        >
          <mesh
            geometry={nodes.Cube003.geometry}
            material={screenMat.current}
          />
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={structureMat.current}
          />
          <Light color={colors[marcello][3]} position={[1, 0, 0]} />
          <Light color={colors[marcello][4]} position={[-12, 0, -40]} />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/p.glb");
